**** Pizza Sales Analysis ****
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Total Revenue Generated
  
SELECT SUM(total_price) as Total_Revenue
FROM pizza_sales

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Total Pizza Sold

SELECT SUM(quantity) as Total_Pizza_Sold
FROM pizza_sales

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Average Order Value

SELECT SUM(total_price)/count(distinct(order_id)) as Avg_order_value
FROM pizza_sales
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Total Orders
  
SELECT count(distinct(order_id)) as Total_order
FROM pizza_sales
  
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Average Pizza Per Order
  
SELECT CAST(CAST(SUM(quantity) AS DECIMAL(10,2)) / CAST(COUNT(DISTINCT order_id) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS Avg_Pizzas_per_order
FROM pizza_sales

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Daily Trend for Total Orders

SELECT DATENAME(DW, order_date) AS order_day, COUNT(DISTINCT order_id) as total_order
from pizza_sales
group by DATENAME(DW, order_date)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Monthly Trend for Orders

SELECT DATENAME(Month, order_date) AS order_hour, COUNT(DISTINCT order_id) as total_order
from pizza_sales
group by  DATENAME(Month, order_date)
ORDER BY  DATENAME(Month, order_date)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Hourly Trend for Orders

SELECT DATEPART(HOUR, order_time) AS order_hour, COUNT(DISTINCT order_id) as total_order
from pizza_sales
group by  DATEPART(HOUR, order_time)
ORDER BY  DATEPART(HOUR, order_time)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Peak hours Sales
  
SELECT DATEPART(HOUR, order_time) AS order_hr, COUNT(order_id) AS orders
from pizza_sales
group by  DATEPART(HOUR, order_time)
ORDER BY  COUNT(order_id) DESC 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Crest hours Sales

SELECT DATEPART(HOUR, order_time) AS order_hr, COUNT(order_id) AS orders
from pizza_sales
group by  DATEPART(HOUR, order_time)
ORDER BY  COUNT(order_id) ASC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Peak days Sales
  
SELECT TOP 1 order_date, COUNT(order_id) AS orders
from pizza_sales
group by  order_date
ORDER BY  COUNT(order_id) DESC 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Crest Days Sales
  
SELECT TOP 1 order_date, COUNT(order_id) AS orders
from pizza_sales
group by  order_date
ORDER BY  COUNT(order_id) ASC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Pizza bestsellers
  
SELECT Top 1 pizza_name, SUM(quantity)
FROM pizza_sales
group by pizza_name
Order by count(quantity) Desc

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Pizza in least demand
  
SELECT Top 5 pizza_name, SUM(quantity)
FROM pizza_sales
group by pizza_name
Order by count(quantity) ASC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Most revenue generated by Pizza
  
SELECT Top 5 pizza_name, SUM(total_price)
FROM pizza_sales
group by pizza_name
Order by SUM(total_price) DESC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Least revenue generated by Pizza
  
SELECT Top 5 pizza_name, SUM(total_price)
FROM pizza_sales
group by pizza_name
Order by SUM(total_price) ASC

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Total Pizza Sold by Category

SELECT pizza_category, SUM(quantity) As Total_quantity_sold
from pizza_sales
GROUP BY pizza_category
ORDER BY Total_quantity_sold

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Percent of Sales by Pizza Category

SELECT pizza_category, CAST(SUM(total_price) AS decimal(10,2)) as Total_Revenue,
CAST((SUM(total_price)*100)/ (SELECT SUM(total_price) from pizza_sales) as DECIMAL(10,2)) AS Per_Sale
FROM pizza_sales
GROUP BY pizza_category
ORDER BY Per_Sale
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Total Pizza Sold by Size

SELECT pizza_size, SUM(quantity) As Total_quantity_sold
from pizza_sales
GROUP BY pizza_size
ORDER BY Total_quantity_sold

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--  Percent of Sales by Pizza Size

SELECT pizza_size, CAST(SUM(total_price) AS decimal(10,2)) as Total_Revenue,
CAST((SUM(total_price)*100)/ (SELECT SUM(total_price) from pizza_sales) as DECIMAL(10,2)) AS Per_Sale
FROM pizza_sales
GROUP BY pizza_size
ORDER BY Per_Sale

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Order and sales per Pizza

SELECT  Top 10 pizza_name, COUNT (order_id) AS Number_of_Orders,SUM (quantity) AS Number_of_Pizzas, ROUND (SUM (total_price),2) AS Total_revenue
FROM pizza_sales
GROUP BY pizza_name
ORDER BY 2 DESC
